package componentes;

public enum Tokens {
    PALAVRA, OPERADOR_ARITMETICO, OP_RELACIONAL, OP_ATRIBUICAO, OP_LOGICO, SIMBOLO_ESPECIAL,
    IDENTIFICADOR, NUMERO, NUMEROREAL, ERROR, INICIO, INICIO_BLOCO, FIM, FIM_BLOCO, LEIA,
    ESCREVA, ESCREVALN, LINHA, STRING_LITERAL
}
